#!/bin/bash
# Use fuzzy finding to open PDF files
# Based on this answer: https://unix.stackexchange.com/a/799709/589116
set -e

if [ $# -eq 0 ]; then
    PDF_READER="okular"
else
    PDF_READER=$1
fi

if ! $(which fzf >/dev/null 2>&1); then
    echo "fzf is required!"
    exit 1
fi

if ! $(which $PDF_READER >/dev/null 2>&1); then
    echo "$PDF_READER is not found! Switching to evince ..."
    PDF_READER="evince"
    if ! $(which $PDF_READER >/dev/null 2>&1); then
	echo "$PDF_READER is also not found!"
	echo "You can specify your PDF reader with $0 PDF_READER"
	echo "Exit"
	exit 1
    fi
fi

find -type f -name \*.pdf -print0 | fzf --height=40% --read0 --print0 | (xargs -0 -r $PDF_READER 2>/dev/null &)
